### ISSUE TITLE
Add option of displaying Wind as km/h when metric unit is active

### ISSUE THREAD

**Issue by briis** [briis/smartweather#16]
Add configuration option for the *Sensor* component to select a specific unit to display Wind Speed in. Today default is m/s for Metric Units and mph for Imperial Units. A new configuration option will be created where this can be overwritten:

Example:
```yaml
sensor:
  type: smartweather
  wind_unit: kmh #Can be ms, mph or kmh
```
